import PDFDocument from "pdfkit";
import { Readable } from "stream";

interface Exercise {
  id?: string;
  name: string;
  sets: number;
  reps: string;
  rest: number;
  notes: string;
}

interface Meal {
  id?: string;
  name: string;
  timing: string;
  macros: {
    protein: number;
    carbs: number;
    fats: number;
  };
  recipe: string;
}

interface Program {
  name: string;
  description: string;
  programType: string;
  duration: number;
  exercises: Exercise[];
  meals: Meal[];
}

const GOLD_COLOR = "#D4AF37";
const BLACK_COLOR = "#000000";
const WHITE_COLOR = "#FFFFFF";
const GRAY_COLOR = "#666666";

export function generateWorkoutPDF(program: Program): Readable {
  const doc = new PDFDocument({
    size: "A4",
    margin: 40,
  });

  // Title
  doc.fillColor(GOLD_COLOR).fontSize(28).font("Helvetica-Bold").text("W.A.R. COACHING", { align: "center" });
  doc.fillColor(GRAY_COLOR).fontSize(12).font("Helvetica").text("WORKOUT PROGRAM", { align: "center" });
  doc.moveDown(0.5);

  // Program Header
  doc.fillColor(BLACK_COLOR).fontSize(18).font("Helvetica-Bold").text(program.name);
  doc.fillColor(GRAY_COLOR).fontSize(11).font("Helvetica").text(program.description || "");
  doc.fontSize(10).text(`Type: ${program.programType} | Duration: ${program.duration} weeks`);
  doc.moveDown(1);

  // Exercises Section
  doc.fillColor(GOLD_COLOR).fontSize(14).font("Helvetica-Bold").text("EXERCISES");
  doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke(GOLD_COLOR);
  doc.moveDown(0.5);

  if (program.exercises.length > 0) {
    program.exercises.forEach((exercise, idx) => {
      // Exercise name
      doc.fillColor(GOLD_COLOR).fontSize(12).font("Helvetica-Bold").text(`${idx + 1}. ${exercise.name}`);

      // Exercise details
      doc.fillColor(BLACK_COLOR).fontSize(10).font("Helvetica");
      doc.text(`Sets: ${exercise.sets} | Reps: ${exercise.reps} | Rest: ${exercise.rest}s`, { indent: 20 });

      // Notes
      if (exercise.notes) {
        doc.fillColor(GRAY_COLOR).fontSize(9).font("Helvetica-Oblique").text(`Notes: ${exercise.notes}`, { indent: 20, width: 450 });
      }

      doc.moveDown(0.3);
    });
  } else {
    doc.fillColor(GRAY_COLOR).fontSize(10).font("Helvetica").text("No exercises assigned yet.");
  }

  doc.moveDown(1);

  // Meals Section
  doc.fillColor(GOLD_COLOR).fontSize(14).font("Helvetica-Bold").text("NUTRITION PLAN");
  doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke(GOLD_COLOR);
  doc.moveDown(0.5);

  if (program.meals.length > 0) {
    program.meals.forEach((meal, idx) => {
      // Meal name and timing
      doc.fillColor(GOLD_COLOR).fontSize(12).font("Helvetica-Bold").text(`${idx + 1}. ${meal.name} (${meal.timing})`);

      // Macros
      doc.fillColor(BLACK_COLOR).fontSize(10).font("Helvetica");
      doc.text(`P: ${meal.macros.protein}g | C: ${meal.macros.carbs}g | F: ${meal.macros.fats}g`, { indent: 20 });

      // Recipe
      if (meal.recipe) {
        doc.fillColor(GRAY_COLOR).fontSize(9).font("Helvetica-Oblique").text(`Recipe: ${meal.recipe}`, { indent: 20, width: 450 });
      }

      doc.moveDown(0.3);
    });
  } else {
    doc.fillColor(GRAY_COLOR).fontSize(10).font("Helvetica").text("No meals assigned yet.");
  }

  // Footer
  doc.moveDown(1);
  doc.fillColor(GRAY_COLOR).fontSize(8).font("Helvetica").text("Generated by W.A.R. Coaching OS", { align: "center" });
  const now = new Date().toLocaleDateString();
  doc.text(`${now}`, { align: "center" });

  doc.end();
  return doc;
}

export function generateMealPlanPDF(meals: Meal[], programName: string): Readable {
  const doc = new PDFDocument({
    size: "A4",
    margin: 40,
  });

  // Title
  doc.fillColor(GOLD_COLOR).fontSize(28).font("Helvetica-Bold").text("W.A.R. COACHING", { align: "center" });
  doc.fillColor(GRAY_COLOR).fontSize(12).font("Helvetica").text("MEAL PLAN", { align: "center" });
  doc.moveDown(0.5);

  // Program name
  doc.fillColor(BLACK_COLOR).fontSize(16).font("Helvetica-Bold").text(programName);
  doc.moveDown(0.5);

  // Meals
  meals.forEach((meal, idx) => {
    // Meal header
    doc.fillColor(GOLD_COLOR).fontSize(12).font("Helvetica-Bold").text(`${idx + 1}. ${meal.name}`);

    // Timing
    doc.fillColor(BLACK_COLOR).fontSize(10).font("Helvetica").text(`Timing: ${meal.timing}`, { indent: 20 });

    // Macros
    doc.fontSize(10).text(`Macros: P: ${meal.macros.protein}g | C: ${meal.macros.carbs}g | F: ${meal.macros.fats}g`, { indent: 20 });

    // Recipe
    if (meal.recipe) {
      doc.fillColor(GRAY_COLOR).fontSize(9).font("Helvetica").text(`Recipe: ${meal.recipe}`, { indent: 20, width: 450 });
    }

    doc.moveDown(0.5);

    // Page break if needed
    if (idx < meals.length - 1 && doc.y > 700) {
      doc.addPage();
    }
  });

  // Footer
  doc.moveDown(1);
  doc.fillColor(GRAY_COLOR).fontSize(8).font("Helvetica").text("Generated by W.A.R. Coaching OS", { align: "center" });
  const now = new Date().toLocaleDateString();
  doc.text(`${now}`, { align: "center" });

  doc.end();
  return doc;
}
